---
# Source: zeebe-cluster/templates/service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zeebe-monitor
  labels:
      release: metrics
spec:
  selector:
    matchLabels:
      app: zeebe
  endpoints:
      - honorLabels: true
        port: http
        interval: 10s
