{
 "title": "Zeebe",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(jvm_info, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(jvm_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "partition",
    "query": "label_values(zeebe_stream_processor_events_total{namespace=~\"$namespace\", pod=~\"$pod\"}, partition)"
   }
  ]
 },
 "panels": [
  {
   "title": "General Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Roles",
     "type": "table",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "atomix_role{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}} {{partitionGroupName}} {{partition}}"
      }
     ]
    },
    {
     "title": "Pod Restarts",
     "type": "graph",
     "description": "Shows when and how often a pod was restarted.  The graph is zero when the pod is ready. With this it is also possible to determine how long it take for the pod to come ready again.",
     "gridPos": { "h": 9, "w": 9, "x": 5, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "1 - kube_pod_container_status_ready{pod=~\".*\", pod!~\"curator.*|worker.*|starter.*\", namespace=\"$namespace\"}",
       "legendFormat": "{{pod}} restart"
      },
      {
       "expr": "sum(rate(kube_pod_container_status_ready{container=\"worker\",namespace=\"$namespace\"}[1m])) or vector(1)",
       "legendFormat": "Worker restart"
      },
      {
       "expr": "sum(rate(kube_pod_container_status_ready{container=\"starter\",namespace=\"$namespace\"}[1m])) or vector(1)",
       "legendFormat": "Starter Restart"
      }
     ]
    },
    {
     "title": "Partition health ",
     "type": "table",
     "gridPos": { "h": 9, "w": 5, "x": 14, "y": 1 },
     "targets": [
      {
       "expr": "zeebe_health{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}} {{partition}}"
      }
     ]
    },
    {
     "title": "Running",
     "type": "table",
     "description": "Displays the current running pods in the namespace.",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Processing per Partition",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_stream_processor_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=~\"written|processed\"}[1m])) by (pod, partition, processor, action)",
       "legendFormat": "{{pod}}-{{partition}}-{{processor}}-{{action}}"
      },
      {
       "expr": "sum(rate(zeebe_exporter_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (pod, partition, exporter)",
       "legendFormat": "{{pod}}-{{partition}}-{{exporter}}"
      }
     ]
    },
    {
     "title": "Completed Processes in avg overtime per sec",
     "type": "singlestat",
     "description": "Takes the avg of all completed processes per second over the given time range.",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 10 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=\"completed\", type=\"PROCESS\"}[1m]))",
       "legendFormat": "{{type}} {{action}}"
      }
     ]
    },
    {
     "title": "Current Events",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (type, action)",
       "legendFormat": "{{type}} {{action}}"
      }
     ]
    },
    {
     "title": "Completed Tasks in avg overtime per sec",
     "type": "singlestat",
     "description": "Takes the avg of all completed tasks per second over the given time range.",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 14 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=\"completed\", type=\"SERVICE_TASK\"}[1m]))",
       "legendFormat": "{{type}} {{action}}"
      }
     ]
    },
    {
     "title": "Append Backpressure",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_deferred_append_count_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition)",
       "legendFormat": "deferred-{{partition}}"
      },
      {
       "expr": "sum(rate(zeebe_try_to_append_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition)",
       "legendFormat": "try-to-append-{{partition}}"
      },
      {
       "expr": "sum(zeebe_backpressure_append_limit{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}) by (partition)",
       "legendFormat": "queue-limit-{{partition}}"
      },
      {
       "expr": "zeebe_backpressure_inflight_append_count{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"} ",
       "legendFormat": "Inflight-for-{{partition}}"
      }
     ]
    },
    {
     "title": "Command API Backpressure",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_dropped_request_count_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition)",
       "legendFormat": "dropped-{{partition}}"
      },
      {
       "expr": "sum(rate(zeebe_received_request_count_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition)",
       "legendFormat": "received-{{partition}}"
      },
      {
       "expr": "sum(zeebe_backpressure_requests_limit{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}) by (partition)",
       "legendFormat": "queue-limit-{{partition}}"
      },
      {
       "expr": "zeebe_backpressure_inflight_requests_count{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}",
       "legendFormat": "inflight-{{partition}}"
      }
     ]
    },
    {
     "title": "GRPC Requests handled per sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total[1m])) by (grpc_method)",
       "legendFormat": "{{grpc_method}} Request"
      }
     ]
    },
    {
     "title": "Client Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_started_total{namespace=~\"$namespace\"}[1m])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      },
      {
       "expr": "sum(rate(grpc_client_completed{namespace=~\"$namespace\"}[1m])) by (grpc_method, code)",
       "legendFormat": "{{grpc_method}} ({{code}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Instance Events per second (range = 1m)",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", type=\"PROCESS\"}[1m])) by (action)"
      }
     ]
    },
    {
     "title": "Job events per second (range = 1m)",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_job_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (action)",
       "legendFormat": "Stream Processor"
      }
     ]
    },
    {
     "title": "Workflow Instance Events",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", type=\"PROCESS\"}) by (action)",
       "legendFormat": "Workflow Instance ({{action}})"
      },
      {
       "expr": "sum(zeebe_job_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}) by (action)",
       "legendFormat": "Job ({{action}})"
      }
     ]
    },
    {
     "title": "Workflow Instance Events per second (range = 1m)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", type=\"PROCESS\"}[1m])) by (action)",
       "legendFormat": "Workflow Instance ({{action}})"
      },
      {
       "expr": "sum(rate(zeebe_job_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (action)",
       "legendFormat": "Job ({{action}})"
      }
     ]
    },
    {
     "title": "Stream Processor Events",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_stream_processor_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}) by (action, processor)",
       "legendFormat": "{{processor}} ({{action}})"
      },
      {
       "expr": "sum(zeebe_exporter_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}) by (action, processor)",
       "legendFormat": "exporter ({{action}})"
      }
     ]
    },
    {
     "title": "Stream Processor Events per second (range = 1m)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_stream_processor_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (action, processor)",
       "legendFormat": "{{processor}} ({{action}})"
      },
      {
       "expr": "sum(rate(zeebe_exporter_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (action, processor)",
       "legendFormat": "exporter ({{action}})"
      }
     ]
    },
    {
     "title": "Running Workflow Instances",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_running_workflow_instances_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"})",
       "legendFormat": "Workflow Instance"
      },
      {
       "expr": "sum(zeebe_pending_jobs_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"})",
       "legendFormat": "Jobs"
      },
      {
       "expr": "sum(zeebe_pending_incidents_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"})",
       "legendFormat": "Incidents"
      }
     ]
    },
    {
     "title": "Stream Processor vs Exporter",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_stream_processor_events_total{namespace=~\"$namespace\", action=~\"skipped|processed\", partition=~\"$partition\", pod=~\"$pod\"}) - sum(zeebe_exporter_events_total{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"})",
       "legendFormat": "Events processed but not exported"
      }
     ]
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Snapshot Count",
     "type": "graph",
     "description": "Total number of committed snapshots on disk",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zeebe_snapshot_count{namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot Operation Duration",
     "type": "graph",
     "description": "Approximate duration of taking a single snapshot from the processor point-of-view (without replication or committing).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "zeebe_snapshot_duration_milliseconds{namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot Size",
     "type": "graph",
     "description": "Size in bytes of snapshots on disk",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "zeebe_snapshot_size_bytes{namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot Files Sizes (1m)",
     "type": "heatmap",
     "description": "Distribution of snapshot file sizes - each snapshot may be comprised of many files, and this shows approximately how \"big\" files there are and how many \"small\" files.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_snapshot_file_size_megabytes_bucket{namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Snapshot Replications",
     "type": "graph",
     "description": "On-going snapshot replications from the receiver point-of-view.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zeebe_snapshot_replication_count{namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot Replication Duration",
     "type": "graph",
     "description": "Approximate duration of replicating a snapshot, from the receiver point-of-view.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "zeebe_snapshot_replication_duration_milliseconds{namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} RSS"
      }
     ]
    },
    {
     "title": "JVM Memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{namespace=~\"$namespace\",pod=~\"$pod\",area=\"heap\"}",
       "legendFormat": "{{pod}} JVM heap"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", cluster=\"\", namespace=~\"$namespace\", image!=\"\", pod_name=~\"$pod\", container_name!=\"POD\"}[1m]))",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Buffer Pool Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (jvm_buffer_pool_used_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}) by (namespace,pod,pool)",
       "legendFormat": "Used {{pod}}:{{pool}}"
      }
     ]
    },
    {
     "title": "File descriptors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(process_open_fds{namespace=~\"$namespace\",pod=~\"$pod\"} / process_max_fds{namespace=~\"$namespace\",pod=~\"$pod\"}) * 100",
       "legendFormat": "{{pod}} used fds"
      },
      {}
     ]
    },
    {
     "title": "PVC Disk Available",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"}",
       "legendFormat": "{{persistentvolumeclaim}} ({{namespace}})"
      }
     ]
    },
    {
     "title": "PVC Disk Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\".*zeebe.*\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\".*zeebe.*\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read bytes/s [1m]",
     "type": "graph",
     "description": "Shows the bytes read per second for the zeebe pods in the select namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{namespace=~\"$namespace\", pod=~\"$namespace.*\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Written bytes/s [1m]",
     "type": "graph",
     "description": "Shows the written bytes per second by the Zeebe pods in the selected namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod=~\"$namespace.*\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network bytes/s transmitted [1m]",
     "type": "graph",
     "description": "Shows how many bytes the Zeebe Pods transmit per second in the selected namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$namespace.*\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network bytes/s received [1m]",
     "type": "graph",
     "description": "Shows how many bytes the Zeebe Pods have received per second in the selected namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\"$namespace.*\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Processing Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Processing Latency (Command)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(zeebe_stream_processor_latency_bucket{namespace=~\"$namespace\",partition=~\"$partition\", recordType=\"COMMAND\"}[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processing Latency (Event)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(zeebe_stream_processor_latency_bucket{namespace=~\"$namespace\",partition=~\"$partition\", recordType=\"EVENT\"}[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processing Execution Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(zeebe_workflow_instance_execution_time_bucket{namespace=~\"$namespace\",partition=~\"$partition\"}[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Job Activation Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(zeebe_job_activation_time_bucket{namespace=~\"$namespace\",partition=~\"$partition\"}[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Job Life Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(zeebe_job_life_time_bucket{namespace=~\"$namespace\",partition=~\"$partition\"}[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(grpc_server_handled_total{namespace=~\"$namespace\", pod=~\"$pod\"}) by (grpc_method, code)",
       "legendFormat": "{{grpc_method}} ({{code}})"
      }
     ]
    },
    {
     "title": "gRPC requests per second (range = 1m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (grpc_method, code)",
       "legendFormat": "{{grpc_method}} ({{code}})"
      },
      {
       "expr": "sum(rate(grpc_server_handled_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m]))",
       "legendFormat": "Total requests completed"
      }
     ]
    },
    {
     "title": "Create Workflow Instance Latency (gRPC)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{grpc_method=\"CreateWorkflowInstance\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Activate Jobs Latency (gRPC)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 70 },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{grpc_method=\"ActivateJobs\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Complete Job Latency (gRPC)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 70 },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{grpc_method=\"CompleteJob\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Atomix",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compacting time",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "sum(increase(atomix_compaction_time_ms_bucket{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[5m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Segment Creation Time",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
     "targets": [
      {
       "expr": "sum(increase(atomix_segment_creation_time_bucket{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Snapshot Replication Duration",
     "type": "graph",
     "description": "Approximate Install RPC as measured by the follower.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "atomix_snapshot_replication_duration_milliseconds{namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot Replications",
     "type": "graph",
     "description": "Ongoing snapshot replications per partition, from the follower point-of-view.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "atomix_snapshot_replication_count{namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} {{partitionGroupName}}-{{partition}}"
      }
     ]
    },
    {
     "title": "Segment Flush Latency",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
     "targets": [
      {
       "expr": "sum(increase(atomix_segment_flush_time_bucket{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Append Entry Latency",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
     "targets": [
      {
       "expr": "sum(increase(atomix_append_entries_latency_bucket{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Time Between Heartbeats",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "targets": [
      {
       "expr": "sum(increase(atomix_heartbeat_time_in_s_bucket{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Heartbeat Miss Counts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(atomix_heartbeat_miss_count{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}[1m])) by (pod, partition)",
       "legendFormat": "{{pod}} - {{partition}}"
      }
     ]
    },
    {
     "title": "Role Changes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 110 },
     "yaxes": [
      { "format": "short", "label": "Role" }
     ],
     "targets": [
      {
       "expr": "atomix_role{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}} {{partition}} {{partitionGroupName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Elasticsearch Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elasticsearch Exporter (Flush Duration)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_elasticsearch_exporter_flush_duration_seconds_bucket{namespace=~\"$namespace\", partition=~\"$partition\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Elasticsearch Exporter (Bulk Size)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_elasticsearch_exporter_bulk_size_bucket{namespace=~\"$namespace\", partition=~\"$partition\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Elasticsearch disk usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "percentunit", "label": "Disk Usage %" }
     ],
     "targets": [
      {
       "expr": "(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"elastic.*\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"elastic.*\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  }
 ]
}